      sequenceDiagram
            %% Presentation Layer
            participant CLI as CLI Entry
            participant Output as CLI Output

            %% Infrastructure Layer
            participant Infra as Infrastructure

            %% Application Layer
            participant App as Application

            CLI->>Infra: Collect Python Files
            Infra->>Infra: Extract Functions with @examon
            Infra->>App: Create Question Object
            App->>App: RemovePythonDecorators
            App->>App: AppendPrint
            App->>App: ChoicesDecorator
            App->>App: PrintLogsDecorator
            App->>App: MetricsDecorator
            App->>App: UniqueIdDecorator
            App->>Infra: JSONAdapter: Serialize json
            Infra->>Output: Output Results
